networks:
  assignment_network:
    driver: bridge

services:
  mongodb:
    image: mongo
    container_name: assignment_mongodb
    networks:
      - assignment_network
    ports:
      - "27017:27017"

  api:
    image: asset_api:v1
    container_name: assignment_api
    networks:
      - assignment_network
    ports:
      - "5282:5282"
    volumes:
      - D:\Data.txt:/app/Data.txt
    depends_on:
      - mongodb

  ui:
    build: UI/.
    container_name: assignment_ui
    networks:
      - assignment_network
    ports:
      - "8080:8080"
    depends_on:
      - api
